# Generated by Django 4.1.7 on 2023-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='house',
            field=models.ImageField(max_length=10, upload_to='', verbose_name='Номер дома:'),
        ),
        migrations.AlterField(
            model_name='addres',
            name='region',
            field=models.CharField(max_length=30, verbose_name='Регион:'),
        ),
        migrations.AlterField(
            model_name='addres',
            name='street',
            field=models.CharField(max_length=10, verbose_name='Улица:'),
        ),
        migrations.AlterField(
            model_name='addres',
            name='town',
            field=models.CharField(max_length=15, verbose_name='Город:'),
        ),
    ]
