# Generated by Django 4.1.7 on 2023-04-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_addres_house_alter_addres_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plase_of_work', models.CharField(max_length=30, verbose_name='Место работы:')),
                ('adress_of_work', models.IntegerField(max_length=20, verbose_name='Адрес работы:')),
                ('education', models.CharField(choices=[('n', ' Среднее профессиональное'), ('n', ' Бакалавриат'), ('n', ' Специалитет, магистратура'), ('n', ' Подготовка кадров высшей квалификации')], max_length=1, verbose_name='Образование:')),
            ],
        ),
        migrations.AlterField(
            model_name='addres',
            name='house',
            field=models.IntegerField(max_length=10, verbose_name='Номер дома:'),
        ),
    ]
