# Generated by Django 4.1.7 on 2023-05-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_news_users_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='images/news', verbose_name='Картинка'),
        ),
    ]
