# Generated by Django 4.1.7 on 2023-05-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.categories'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='Текст статьи', verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Заголовок', max_length=100, verbose_name='Заголовок статьи'),
        ),
    ]
